name: "python tests"
on:
  pull_request:
  push:
    branches: [latest]
jobs:
  mamba:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
      with:
        fetch-depth: 0

    - name: install dependencies
      shell: bash -l {0}
      run: mamba install git compilers maturin pytest pandas

    - name: test
      shell: bash -l {0}
      run: pytest
